//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AldeasInfantilesDBEntities : DbContext
    {
        public AldeasInfantilesDBEntities()
            : base("name=AldeasInfantilesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListaArea> ListaAreas { get; set; }
        public virtual DbSet<ListaCiudad> ListaCiudades { get; set; }
        public virtual DbSet<ListaFacility> ListaFacilities { get; set; }
        public virtual DbSet<ListaFilial> ListaFilials { get; set; }
        public virtual DbSet<ListaPrograma> ListaProgramas { get; set; }
        public virtual DbSet<ListaSeccion> ListaSeccions { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumentoes { get; set; }
        public virtual DbSet<ListaProfesion> ListaProfesions { get; set; }
        public virtual DbSet<TipoEstadoCivil> TipoEstadoCivils { get; set; }
        public virtual DbSet<ListaDepartamento> ListaDepartamentoes { get; set; }
        public virtual DbSet<TipoEstudio> TipoEstudios { get; set; }
        public virtual DbSet<ListaCargo> ListaCargoes { get; set; }
        public virtual DbSet<Seguro> Seguros { get; set; }
        public virtual DbSet<TipoAFP> TipoAFPs { get; set; }
        public virtual DbSet<TipoInicio> TipoInicios { get; set; }
        public virtual DbSet<TipoContratacion> TipoContratacions { get; set; }
        public virtual DbSet<ListaEscalaSalarial> ListaEscalaSalarials { get; set; }
        public virtual DbSet<ListaAFP> ListaAFPs { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<BajaPersonal> BajaPersonals { get; set; }
        public virtual DbSet<TipoRetiro> TipoRetiroes { get; set; }
    }
}
