//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CierreContable()
        {
            this.Comprobantes = new HashSet<Comprobante>();
        }
    
        public int Id { get; set; }
        public int CiudadId { get; set; }
        public short EstadoCierreId { get; set; }
        public short PeriodoCierreId { get; set; }
        public short TipoCierreId { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual EstadosCierre EstadosCierre { get; set; }
        public virtual PeriodoCierre PeriodoCierre { get; set; }
        public virtual TiposCierre TiposCierre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante> Comprobantes { get; set; }
    }
}
