//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comprobante()
        {
            this.CuentasAsientos = new HashSet<CuentaAsiento>();
            this.TraspasoProgramaAN = new HashSet<TraspasosPrograma>();
            this.TraspasoPrograma = new HashSet<TraspasosPrograma>();
        }
    
        public int Id { get; set; }
        public int FacilityId { get; set; }
        public int TipoComprobanteId { get; set; }
        public Nullable<int> CuentaBancoId { get; set; }
        public string NumeroComprobante { get; set; }
        public System.DateTime FechaComprobante { get; set; }
        public string Beneficiario { get; set; }
        public string Glosa { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public short TipoMonedaId { get; set; }
        public string NumeroCheque { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int CiudadId { get; set; }
        public short EstadoComprobanteId { get; set; }
        public string Observaciones { get; set; }
        public int CierreContableId { get; set; }
    
        public virtual CuentaBanco CuentaBanco { get; set; }
        public virtual TiposComprobante TiposComprobante { get; set; }
        public virtual TipoMoneda TiposMoneda { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaAsiento> CuentasAsientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraspasosPrograma> TraspasoProgramaAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraspasosPrograma> TraspasoPrograma { get; set; }
        public virtual EstadosComprobante EstadosComprobante { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual CierreContable CierreContable { get; set; }
    }
}
