//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaContable()
        {
            this.CuentasAsientos = new HashSet<CuentaAsiento>();
            this.Recursos = new HashSet<Recurso>();
            this.PlantillasCuentas = new HashSet<PlantillaCuenta>();
            this.FacilitiesCuentasContables = new HashSet<FacilityCuentaContable>();
            this.PlanProgramaticoCuentas = new HashSet<PlanProgramaticoCuenta>();
        }
    
        public int Id { get; set; }
        public int CuentaNavisionId { get; set; }
        public byte TipoCuentaId { get; set; }
        public int ContraparteId { get; set; }
        public string Numero { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<short> NivelCuentaId { get; set; }
        public Nullable<short> GrupoCuentaNavId { get; set; }
        public bool Elegible { get; set; }
    
        public virtual Contraparte Contraparte { get; set; }
        public virtual CuentaNavision CuentaNavision { get; set; }
        public virtual TiposCuenta TiposCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaAsiento> CuentasAsientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recurso> Recursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantillaCuenta> PlantillasCuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilityCuentaContable> FacilitiesCuentasContables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanProgramaticoCuenta> PlanProgramaticoCuentas { get; set; }
    }
}
