//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaAsiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaAsiento()
        {
            this.EstadosCuentas = new HashSet<EstadoCuenta>();
            this.EstadosCuentas1 = new HashSet<EstadoCuenta>();
        }
    
        public int Id { get; set; }
        public int ComprobanteId { get; set; }
        public int CuentaContableId { get; set; }
        public string Glosa { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public int TerritorioId { get; set; }
        public int PlanProgramaticoId { get; set; }
        public int ContraparteId { get; set; }
        public Nullable<int> AnexoTributarioId { get; set; }
        public Nullable<int> CodigoAuditoriaId { get; set; }
        public Nullable<int> AccionNacionalId { get; set; }
        public bool EsDebe { get; set; }
        public bool EsAjuste { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string NotasAdicionales { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> MarcoLogicoId { get; set; }
    
        public virtual AccionesNacionale AccionesNacionale { get; set; }
        public virtual AnexosTributario AnexosTributario { get; set; }
        public virtual CodigosAuditoria CodigosAuditoria { get; set; }
        public virtual Comprobante Comprobante { get; set; }
        public virtual Contraparte Contraparte { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual PlanProgramatico PlanProgramatico { get; set; }
        public virtual Territorio Territorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuenta> EstadosCuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuenta> EstadosCuentas1 { get; set; }
        public virtual CodigoMarcoLogico CodigoMarcoLogico { get; set; }
    }
}
