//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCuenta
    {
        public int Id { get; set; }
        public short TipoEstadoCuentaId { get; set; }
        public Nullable<int> DebeCiudadId { get; set; }
        public Nullable<int> DebeFacilityId { get; set; }
        public Nullable<int> DebeCuentaAsientoId { get; set; }
        public Nullable<int> HaberCiudadId { get; set; }
        public Nullable<int> HaberFacilityId { get; set; }
        public Nullable<int> HaberCuentaAsientoId { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Ciudad CiudadDebe { get; set; }
        public virtual Ciudad CiudadHaber { get; set; }
        public virtual CuentaAsiento CuentasAsientoDebe { get; set; }
        public virtual CuentaAsiento CuentasAsientoHaber { get; set; }
        public virtual Facility FacilityDebe { get; set; }
        public virtual Facility FacilityHaber { get; set; }
        public virtual TiposEstadosCuenta TiposEstadosCuenta { get; set; }
    }
}
