//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrograma
    {
        public string codigoPrograma { get; set; }
        public string codigoTipoPrograma { get; set; }
        public string Descripcion { get; set; }
        public string codigoFilial { get; set; }
        public Nullable<int> idFacility { get; set; }
    }
}
