//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observacion
    {
        public int Id { get; set; }
        public short TipoObservacionId { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string Descripcion { get; set; }
        public string FilasObservadas { get; set; }
        public bool Aprobado { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool EsNacional { get; set; }
        public Nullable<int> CiudadId { get; set; }
    
        public virtual TipoObservacion TipoObservacion { get; set; }
    }
}
