//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRO
    {
        public int ID { get; set; }
        public string COD_PARAMETRO { get; set; }
        public string DES_PARAMETRO { get; set; }
        public string COD_PARAM1 { get; set; }
        public string DES_PARAM1 { get; set; }
        public string COD_PARAM2 { get; set; }
        public string DES_PARAM2 { get; set; }
        public string COD_PARAM3 { get; set; }
        public string DES_PARAM3 { get; set; }
        public string COD_PARAM4 { get; set; }
        public string DES_PARAM4 { get; set; }
        public string COD_PARAM5 { get; set; }
        public string DES_PARAM5 { get; set; }
    }
}
