//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODOS_PLANILLAS
    {
        public int Id { get; set; }
        public short Gestion { get; set; }
        public short Mes { get; set; }
        public short EstadoPlanillaId { get; set; }
        public bool EsRetroactivo { get; set; }
        public Nullable<int> RetroactivoId { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual ESTADOS_PLANILLAS ESTADOS_PLANILLAS { get; set; }
        public virtual RETROACTIVO RETROACTIVO { get; set; }
    }
}
