//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORCENTAJE_APORTE_NACIONAL_SOL
    {
        public short ID { get; set; }
        public decimal INTERVALO_INICIAL { get; set; }
        public decimal INTERVALO_FINAL { get; set; }
        public decimal PORCENTAJE { get; set; }
        public short TIPO { get; set; }
    }
}
