//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestoFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PresupuestoFacility()
        {
            this.PresupuestosFacilitiesCompartidos = new HashSet<PresupuestoFacilityCompartido>();
        }
    
        public int Id { get; set; }
        public int PresupuestoId { get; set; }
        public int FacilityId { get; set; }
        public short EstadoPresupuestoId { get; set; }
        public decimal Monto { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual EstadoPresupuesto EstadoPresupuesto { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual Presupuesto Presupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestoFacilityCompartido> PresupuestosFacilitiesCompartidos { get; set; }
    }
}
