//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_UFVS
    {
        public int ID { get; set; }
        public decimal UFV_ACTUAL { get; set; }
        public decimal UFV_ANTERIOR { get; set; }
        public string FECHA_UFV { get; set; }
    }
}
