//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retencion
    {
        public int Id { get; set; }
        public Nullable<int> ComprobanteId { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public Nullable<short> TipoRetencionId { get; set; }
        public Nullable<decimal> ImporteRetencion { get; set; }
        public Nullable<decimal> ImporteRetencionIT { get; set; }
        public Nullable<bool> Retenido { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual TiposRetencion TiposRetencion { get; set; }
    }
}
