//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraspasosPrograma
    {
        public int Id { get; set; }
        public Nullable<int> ComprobanteProgramaId { get; set; }
        public Nullable<int> ComprobanteANId { get; set; }
        public string CuentaTransitoriaNumero { get; set; }
        public decimal MontoTraspaso { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Comprobante ComprobanteAN { get; set; }
        public virtual Comprobante ComprobanteProg { get; set; }
    }
}
