//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCierreContable
    {
        public int CiudadId { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Estado { get; set; }
        public int CierreContableId { get; set; }
        public short PeriodoCierreId { get; set; }
    }
}
