//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VComprobante
    {
        public int IdCuentaAsiento { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public string Glosa_CuentasAsientos { get; set; }
        public int CuentaContableId { get; set; }
        public int IdCuentaContable { get; set; }
        public string Nombre { get; set; }
        public string Numero { get; set; }
        public string Descripcion_CuentaContable { get; set; }
        public int IdComprobante { get; set; }
        public string Beneficiario { get; set; }
        public int FacilityId { get; set; }
        public string Glosa_comprobante { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string NumeroCheque { get; set; }
        public string Cod_Facility { get; set; }
        public string Nombre_Facility { get; set; }
        public int IdCodAuditoria { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    }
}
