//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPLANILLA_MINISTERIO
    {
        public string NUMERO_DOC { get; set; }
        public string EXPEDIDO { get; set; }
        public string AFP_APORTA { get; set; }
        public string NUA { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string APELLIDO_CASADA { get; set; }
        public string NOMBRES { get; set; }
        public string NACIONALIDAD { get; set; }
        public string FECHA_NACIMIENTO { get; set; }
        public string SEXO { get; set; }
        public string CARGO { get; set; }
        public string FECHA_INGRESO { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public string FECHA_RETIRO { get; set; }
        public Nullable<int> DIAS_TRAB { get; set; }
        public Nullable<int> CARGA_HORARIA { get; set; }
        public Nullable<decimal> HABER_BASICO { get; set; }
        public Nullable<decimal> BONO_ANTIGUEDAD { get; set; }
        public decimal ASIG_SOS { get; set; }
        public int NUMERO { get; set; }
        public int MONTO_PAGADO { get; set; }
        public int BONO_PRODUCCION { get; set; }
        public decimal OTROS_BONOS { get; set; }
        public int NUMERO_DOMINICAL { get; set; }
        public int DOMINICAL { get; set; }
        public Nullable<decimal> TOTAL_GANADO { get; set; }
        public Nullable<decimal> AFP { get; set; }
        public Nullable<decimal> RC_IVA { get; set; }
        public Nullable<decimal> OTROS_DESCUENTOS { get; set; }
        public Nullable<decimal> TOTAL_DESCUENTO { get; set; }
        public Nullable<decimal> LIQ_PAGABLE { get; set; }
        public string FILIAL { get; set; }
        public string PROGRAMA { get; set; }
        public string SECCION { get; set; }
        public string ESCALA_SALARIAL { get; set; }
        public int MES { get; set; }
        public string GESTION { get; set; }
        public string MES_CIERRE { get; set; }
    }
}
