//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cerberus.Sos.Accounting.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recurso()
        {
            this.RecursosMeses = new HashSet<RecursoMes>();
        }
    
        public int Id { get; set; }
        public int PresupuestoId { get; set; }
        public int PlanProgramaticoId { get; set; }
        public int CiudadId { get; set; }
        public int CuentaContableId { get; set; }
        public int FacilityId { get; set; }
        public int TerritorioId { get; set; }
        public int ContraparteId { get; set; }
        public int CodigoAuditoriaId { get; set; }
        public int AccionNacionalId { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public int Gestion { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual AccionesNacionale AccionesNacionale { get; set; }
        public virtual CodigosAuditoria CodigosAuditoria { get; set; }
        public virtual Contraparte Contraparte { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual PlanProgramatico PlanProgramatico { get; set; }
        public virtual Presupuesto Presupuesto { get; set; }
        public virtual Territorio Territorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecursoMes> RecursosMeses { get; set; }
    }
}
